{% set name = "petl" %}
{% set version = "1.7.7" %}
{% set sha256 = "75976361472da58b12780fe07c1520aebeae89ffa51df3a2c1760ef85de32bff" %}

## github.com/petl-developers/petl-feedstock

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - pytest
  run:
    - python
    - pytest

test:
  imports:
    - petl
  requires:
    - pytest
  commands:
    - pytest --verbose petl

about:
  home: http://github.com/petl-developers/petl
  license: MIT
  license_file: LICENSE.txt
  summary: A Python package for extracting, transforming and loading tables of data.
  doc_url: http://petl.readthedocs.io/
  dev_url: https://github.com/petl-developers/petl

extra:
  recipe-maintainers:
    - alimanfoo
    - timbledum
    - juarezr
    - arturponinski
