{% set name = "petl" %}
{% set version = "1.7.8" %}
{% set sha256 = "f6b0100d6a42ca8f5fc84ea7b312fe922b7027cd8d2f7f22144eee0c4dd34a52" %}

## github.com/petl-developers/petl-feedstock

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
    - pytest <7.0.0
  run:
    - python >=3.6
    - pytest <7.0.0

test:
  imports:
    - petl
  requires:
    - pytest <7.0.0
  commands:
    - pytest --verbose petl
  source_files:
    - petl/

about:
  home: http://github.com/petl-developers/petl
  license: MIT
  license_file: LICENSE.txt
  summary: A Python package for extracting, transforming and loading tables of data.
  doc_url: http://petl.readthedocs.io/
  dev_url: https://github.com/petl-developers/petl

extra:
  recipe-maintainers:
    - alimanfoo
    - timbledum
    - juarezr
    - arturponinski
